name: mukchests
services:
  node:
    type: node:16
    scanner: false
    build:
      - npm install
    command: npm start
tooling:
  npm:
    service: node
  node:
    service: node
proxy:
  node:
    - mukchests.lndo.site:3000